### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by onsela** [jozefchutka/YCanvas#3]
Seems like a very useful library but it would be great if you provided some directives on how to setup the projects. I am still trying to figure out how to open and compile the Feathers demo in Flash Builder. Getting lots of compile errors...

**Comment by jozefchutka** [comment]
hi onsela, project files are commited in the repository. it might be that commited project files conflicts with your pc setup, they should not have been commited at all. you can always remove it and create new projects:
1. **YCanvasLibrary** - use air 3.8 or later, compile for flash player 11.2, additional compiler argument "-locale en_US -swf-version=13", main source folder: src\main\actionscript, source paths: libs\starling-1.4, libs\yoz ... try to compile this 
2. **YCanvasMapLibrary** - use air 3.8 or later, compile for flash player 11.2, additional compiler argument "-locale en_US -swf-version=13", main source folder: src\main\actionscript, source paths: libs\yoz, libs: YCanvasLibrary, greensock.swc ... try compile YCanvasMapLibrary
3. **ApplicationMap** - use air 3.8 or later, additional compiler argument "-locale en_US -swf-version=21", main source folder: src\main\actionscript, source paths: src\main\resources, libs\feathers-1.1.1, libs: YCanvasLibrary, YCanvasMapLibrary
make sure you use wmode direct in your html template
