### ISSUE TITLE
Does this work for Zoomify images?

### ISSUE THREAD

**Issue by colouredFunk** [jozefchutka/YCanvas#6]
created from Photoshop

**Comment by jozefchutka** [comment]
With YCanvas you can implement any tile overlapings projects... I am looking at zoomify requests right now and I do not see any reason why this could not be implemented:
http://www.zoomify.com/images/folders/parisSatellite/TileGroup0/4-1-4.jpg
http://www.zoomify.com/images/folders/parisSatellite/TileGroup1/5-6-10.jpg
you just have to figure out how to translate ycanvas coordinates into request. Have a look at https://github.com/jozefchutka/YCanvas examples code and fork Partition.as to load images from zoomify.
...zoomify does not provides crossdomain.xml though so you have to figure out that one
